/**
   * Product Data
   */
const productData = [
    {
        id: '1',
        image: ['assets/img/shop/catalog/01.jpg', 'assets/img/shop/single/gallery/th01.jpg'],
        category: 'Sneakers & Keds',
        name: 'Women Colorblock Sneakers',
        price: '154.00',
        discount: '',
        rating: 3.5,
        review: 75,
        size: ['7.5', '8', '8.5', '9'],
        colors: [],
        type: 'size',
        cat: 'Sneakers',
        brand: 'adidas'
    },
    {
        id: '2',
        image: ['assets/img/shop/catalog/02.jpg'],
        category: 'Women’s T-shirt',
        name: 'Cotton Lace Blouse',
        price: '28.50',
        discount: '38.50',
        rating: 3,
        review: 50,
        size: [],
        colors: ['#eaeaeb', '#d1dceb', '#f4e6a2', '#f3dcff'],
        type: 'color',
        cat: 'Blouses',
        brand: 'ataylor'
    },
    {
        id: '3',
        image: ['assets/img/shop/catalog/03.jpg'],
        category: 'Women’s Shorts',
        name: 'Mom High Waist Shorts',
        price: '28.50',
        discount: '39.50',
        rating: 5,
        review: 20,
        size: ['XS', 'S', 'M', 'L'],
        colors: [],
        type: 'size',
        cat: 'Shorts',
        brand: 'ataylor'
    },
    {
        id: '4',
        image: ['assets/img/shop/catalog/04.jpg'],
        category: 'Sportswear',
        name: 'Women Sports Jacket',
        price: '68.40',
        discount: '',
        rating: 4,
        review: 70,
        size: ['XS', 'S', 'M', 'L'],
        colors: [],
        type: 'size',
        cat: 'Sportswear',
        brand: 'ataylor'
    },
    {
        id: '5',
        image: ['assets/img/shop/catalog/05.jpg'],
        category: 'Men’s Sunglasses',
        name: 'Polarized Sunglasses',
        price: '',
        discount: '',
        rating: 4.5,
        review: 55,
        size: [],
        colors: [],
        type: 'details',
        cat: 'Classic',
        brand: 'armani'
    },
    {
        id: '6',
        image: ['assets/img/shop/catalog/09.jpg'],
        category: 'Cosmetics',
        name: 'Metallic Lipstick (Crimson)',
        price: '12.99',
        discount: '',
        rating: 3,
        review: 10,
        size: [],
        colors: [],
        type: 'color',
        cat: 'Cosmetics'
    },
    {
        id: '7',
        image: ['assets/img/shop/catalog/07.jpg'],
        category: `Women's Swimwear`,
        name: 'Two-Piece Bikini in Print',
        price: '18.99',
        discount: '',
        rating: 4,
        review: 25,
        size: ['XS', 'S', 'M'],
        colors: [],
        type: 'size',
        cat: 'Swimwear'
    },
    {
        id: '8',
        image: ['assets/img/shop/catalog/26.jpg'],
        category: `Shoes`,
        name: 'Textile Platform Sneakers',
        price: '59.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '9',
        image: ['assets/img/shop/catalog/28.jpg'],
        category: `Shoes`,
        name: 'Leather Platform Sandals',
        price: '79.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '10',
        image: ['assets/img/shop/catalog/29.jpg'],
        category: `Shorts`,
        name: 'Short Chino Shorts',
        price: '24.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '11',
        image: ['assets/img/shop/catalog/30.jpg'],
        category: `T-shirts`,
        name: 'T-shirt with Motif',
        price: '13.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '12',
        image: ['assets/img/shop/catalog/31.jpg'],
        category: `Shoes`,
        name: 'Leather Platform Sandals',
        price: '67.95',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
]

// Men Data
const mensproduct = [
    {
        id: '1',
        image: 'assets/img/shop/catalog/32.jpg',
        category: 'Hats & Caps',
        name: 'Cap with Appliqué',
        price: '15.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '2',
        image: 'assets/img/shop/catalog/33.jpg',
        category: 'T-shirts',
        name: 'Regular Fit Cotton Shirt',
        price: '19.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '3',
        image: 'assets/img/shop/catalog/34.jpg',
        category: 'Accessories',
        name: 'Polarized Sunglasses',
        price: '37.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '4',
        image: 'assets/img/shop/catalog/35.jpg',
        category: 'Shoes',
        name: 'Leather Men’s Sneakers',
        price: '45.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '5',
        image: 'assets/img/shop/catalog/36.jpg',
        category: 'Bags',
        name: 'Swedish Backpack',
        price: '68.95',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '6',
        image: 'assets/img/shop/catalog/37.jpg',
        category: 'Accessories',
        name: 'Stainless Steel Watches',
        price: '542.80',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '7',
        image: 'assets/img/shop/catalog/11.jpg',
        category: 'Sandals',
        name: 'Soft Footbed Sandals',
        price: '99.50',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '8',
        image: 'assets/img/shop/catalog/38.jpg',
        category: 'Shorts',
        name: 'Silver Ringe Cargo Short',
        price: '45.00',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '9',
        image: 'assets/img/shop/catalog/10.jpg',
        category: 'Shorts',
        name: 'Multicolor Bracelets',
        price: '7.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '10',
        image: 'assets/img/shop/catalog/39.jpg',
        category: 'T-shirts',
        name: '3-pack T-shirts Slim Fit',
        price: '21.70',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '11',
        image: 'assets/img/shop/catalog/12.jpg',
        category: 'Hats & Caps',
        name: '3-Color Sun Stash Hat',
        price: '25.9',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '12',
        image: 'assets/img/shop/catalog/06.jpg',
        category: 'Bags',
        name: 'TH Jeans City Backpack',
        price: '79.50',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
]

// For Kids
const kidsproduct = [
    {
        id: '1',
        image: 'assets/img/shop/catalog/40.jpg',
        category: 'Clothing',
        name: 'Girl’s Denim Jacket',
        price: '24.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '2',
        image: 'assets/img/shop/catalog/41.jpg',
        category: 'Shoes',
        name: 'Textile Ballet Flats',
        price: '16.50',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '3',
        image: 'assets/img/shop/catalog/42.jpg',
        category: 'T-shirts',
        name: 'Boys T-shirt with Motif',
        price: '17.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '4',
        image: 'assets/img/shop/catalog/43.jpg',
        category: 'Accessories',
        name: 'Dotted Shoulder Bag',
        price: '23.00',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '5',
        image: 'assets/img/shop/catalog/44.jpg',
        category: 'Hats & Caps',
        name: '2-pack Cotton Sun Hats',
        price: '18.00',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '6',
        image: 'assets/img/shop/catalog/08.jpg',
        category: 'Toys',
        name: 'Soft Panda Teddy Bear',
        price: '14.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '7',
        image: 'assets/img/shop/catalog/45.jpg',
        category: 'T-shirts',
        name: 'Outlined Star Chevron Tee',
        price: '10.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '8',
        image: 'assets/img/shop/catalog/46.jpg',
        category: 'Hats & Caps',
        name: 'Banana Embroidery Cap',
        price: '15.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '9',
        image: 'assets/img/shop/catalog/47.jpg',
        category: 'Shoes',
        name: 'Big Kid Sneakers',
        price: '42.50',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '10',
        image: 'assets/img/shop/catalog/48.jpg',
        category: 'Clothing',
        name: `Boy's Printed Shorts`,
        price: '18.99',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '11',
        image: 'assets/img/shop/catalog/49.jpg',
        category: 'Toys',
        name: 'Unicorn Soft Toy',
        price: '22.50',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    },
    {
        id: '12',
        image: 'assets/img/shop/catalog/50.jpg',
        category: 'Swimwear',
        name: 'Pool Santorini Tankini',
        price: '20.00',
        discount: '',
        rating: 5,
        review: 30,
        size: [],
        colors: [],
        type: 'size'
    }
]

export { productData, mensproduct, kidsproduct }