const ShopGridLsdata = [
    {
        id:'1',
        image:['assets/img/shop/catalog/01.jpg','assets/img/shop/single/gallery/th01.jpg'],
        category: 'Sneakers & Keds',
        name:'Women Colorblock Sneakers',
        price: '154.00',
        discount: '',
        rating: 3.5,
        review:75,
        size:['7.5','8','8.5','9'],
        colors:[],
        type:'size',
        cat:'Sneakers',
        brand:'adidas'
    },
    {
        id:'2',
        image:['assets/img/shop/catalog/02.jpg'],
        category: 'Women’s T-shirt',
        name:'Cotton Lace Blouse',
        price: '28.50',
        discount: '38.50',
        rating:3,
        review:50,
        size:[],
        colors:['#eaeaeb','#d1dceb','#f4e6a2','#f3dcff'],
        type:'color',
        cat:'Blouses',
        brand:'ataylor'
    },
    {
        id:'3',
        image:['assets/img/shop/catalog/03.jpg'],
        category: 'Women’s Shorts',
        name:'Mom High Waist Shorts',
        price: '28.50',
        discount: '39.50',
        rating:5,
        review:20,
        size:['XS','S','M','L'],
        colors:[],
        type:'size',
        cat:'Shorts',
         brand:'ataylor'
    },
    {
        id:'4',
        image:['assets/img/shop/catalog/04.jpg'],
        category: 'Sportswear',
        name:'Women Sports Jacket',
        price: '68.40',
        discount: '',
        rating:4,
        review:70,
        size:['XS','S','M','L'],
        colors:[],
        type:'size',
        cat:'Sportswear',
         brand:'ataylor'
    },
    {
        id:'5',
        image:['assets/img/shop/catalog/05.jpg'],
        category: 'Men’s Sunglasses',
        name:'Polarized Sunglasses',
        price: '',
        discount: '',
        rating:4.5,
        review:55,
        size:[],
        colors:[],
        type:'details',
        cat:'Classic',
         brand:'armani'
    },
    {
        id:'6',
        image:['assets/img/shop/catalog/06.jpg'],
        category: 'Backpacks',
        name:'TH Jeans City Backpack',
        price: '79.50',
        discount: '',
        rating:3,
        review:10,
        size:[],
        colors:['#97947c','#99a8be','#eaeaeb'],
        type:'color',
        cat:'Backpacks'
    },
    {
        id:'7',
        image:['assets/img/shop/catalog/07.jpg'],
        category: `Women's Swimwear`,
        name:'Two-Piece Bikini in Print',
        price: '18.99',
        discount: '',
        rating:4,
        review:25,
        size:['XS','S','M'],
        colors:[],
        type:'size',
        cat:'Swimwear'
    },
    {
        id:'8',
        image:['assets/img/shop/catalog/08.jpg'],
        category: `Kid's Toys`,
        name:'Soft Panda Teddy Bear',
        price: '14.99',
        discount: '',
        rating:5,
        review:30,
        size:[],
        colors:[],
        type:'size'
    },
    {
        id:'9',
        image:['assets/img/shop/catalog/09.jpg'],
        category: 'Cosmetics',
        name:'Metallic Lipstick (Crimson)',
        price: '12.99',
        discount: '',
        rating:3.5,
        review:48,
        size:[],
        colors:['#bd3c82','#ebae81','#ca8799'],
        type:'color',
        cat:'Cosmetics'
    },
    {
        id:'10',
        image:['assets/img/shop/catalog/10.jpg'],
        category: 'Men’s Accessories',
        name:'5-Pack Multicolor Bracelets',
        price: '7.99',
        discount: '',
        rating:5,
        review:33,
        size:[],
        colors:[],
        type:'size',
        cat:'Jewelry'
    },
    {
        id:'11',
        image:['assets/img/shop/catalog/11.jpg'],
        category: 'Men’s Sandals',
        name:'Soft Footbed Sandals',
        price: '99.50',
        discount: '',
        rating:4,
        review:68,
        size:[],
        colors:['#879fb3','#9c6d4a','#333333'],
        type:'color',
        cat:'Sandals',
        brand:'adidas'
    },
    {
        id:'12',
        image:['assets/img/shop/catalog/12.jpg'],
        category: `Women's Swimwear`,
        name:'3-Color Sun Stash Hat',
        price: '25.99',
        discount: '',
        rating:4.5,
        review:12,
        size:['S','M','L'],
        colors:[],
        type:'size',
        cat:'Hats',
    },
    {
        id:'13',
        image:['assets/img/shop/catalog/13.jpg'],
        category: `Men’s T-shirts`,
        name:'Cotton Polo Regular Fit',
        price: '11.50',
        discount: '13.50',
        rating:3,
        review:41,
        size:['S','M','L','XL'],
        colors:[],
        type:'size',
        cat:'T-shirts'
    },
    {
        id:'14',
        image:['assets/img/shop/catalog/14.jpg'],
        category: `Men’s Jeans`,
        name:'Slim Taper Fit Jeans',
        price: '58.99',
        discount: '',
        rating:4,
        review:38,
        size:['S','M','L','XL'],
        colors:[],
        type:'size',
        cat:'Jeans'
    },
    {
        id:'15',
        image:['assets/img/shop/catalog/15.jpg'],
        category: `Men’s Waistcoats`,
        name:'Single-breasted Trenchcoat',
        price: '79.99',
        discount: '',
        rating:3.5,
        review:33,
        size:['M','L','XL'],
        colors:[],
        type:'size',
        cat:'Jackets'
    },
  ];
  
  export { ShopGridLsdata };
  